name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Inject Token into HTML
        run: |
          # This replaces the placeholder in your index.html with your actual secret
          sed -i "s/__GH_TOKEN__/${{ secrets.MY_GITHUB_TOKEN }}/g" index.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
